### ISSUE TITLE
Archiving the repo

### ISSUE THREAD

**Issue by psschwei** [knative-sandbox/container-freezer#217]
We're planning to archive this repo prior to the next Knative release in April. 

Please respond here if you're still using the freezer and/or interested in maintaining it.

**Comment by WoWsj** [comment]
Hello. Can I ask why archive this project?

**Comment by psschwei** [comment]
Lack of community interest / it's not being maintained

**Comment by WoWsj** [comment]
Too bad... I was interested in this feature. 😭

**Comment by emaildanwilson** [comment]
bummer. I was just going to try it out.

**Comment by psschwei** [comment]
If one was still interested in the freezer, the code here can still be used by forking the repo and implementing the code from https://github.com/knative/serving/pull/13830 as part of your own custom queue proxy (for an example of how this might be done, check out the  [security-guard](https://github.com/knative-sandbox/security-guard/blob/main/cmd/queue/main.go)  repo).
