### ISSUE TITLE
Freeze CRI-O containers

### ISSUE THREAD

**Issue by psschwei** [knative-sandbox/container-freezer#52]
Add support for freezing containers using the CRI-O runtime.

**Comment by jwcesign** [comment]
How about the developing processing about this?

**Comment by jwcesign** [comment]
[ ] Prepare testing environment
[ ] Implement CRI-O runtime
[ ] UT 
[ ] E2E testing

**Comment by jwcesign** [comment]
- [x] build cri-o test environment
- [ ] write code for cri-o implement

**Comment by jwcesign** [comment]
related with https://github.com/cri-o/cri-o/issues/5632

**Comment by psschwei** [comment]
Done in #110
